import { Network } from 'alchemy-sdk';
import type { Chain } from '../types';

export const SUPPORTED_CHAINS: Chain[] = [
  {
    id: 'ethereum',
    name: 'Ethereum',
    alchemyNetwork: Network.ETH_MAINNET,
    coingeckoPlatform: 'ethereum',
    nativeSymbol: 'ETH',
    explorerUrl: 'https://etherscan.io',
  },
  {
    id: 'polygon',
    name: 'Polygon',
    alchemyNetwork: Network.MATIC_MAINNET,
    coingeckoPlatform: 'polygon-pos',
    nativeSymbol: 'MATIC',
    explorerUrl: 'https://polygonscan.com',
  },
  {
    id: 'arbitrum',
    name: 'Arbitrum',
    alchemyNetwork: Network.ARB_MAINNET,
    coingeckoPlatform: 'arbitrum-one',
    nativeSymbol: 'ETH',
    explorerUrl: 'https://arbiscan.io',
  },
  {
    id: 'optimism',
    name: 'Optimism',
    alchemyNetwork: Network.OPT_MAINNET,
    coingeckoPlatform: 'optimistic-ethereum',
    nativeSymbol: 'ETH',
    explorerUrl: 'https://optimistic.etherscan.io',
  },
  {
    id: 'base',
    name: 'Base',
    alchemyNetwork: Network.BASE_MAINNET,
    coingeckoPlatform: 'base',
    nativeSymbol: 'ETH',
    explorerUrl: 'https://basescan.org',
  },
  {
    id: 'bsc',
    name: 'BNB Chain',
    alchemyNetwork: Network.BNB_MAINNET,
    coingeckoPlatform: 'binance-smart-chain',
    nativeSymbol: 'BNB',
    explorerUrl: 'https://bscscan.com',
  },
  {
    id: 'avalanche',
    name: 'Avalanche',
    alchemyNetwork: Network.AVAX_MAINNET,
    coingeckoPlatform: 'avalanche',
    nativeSymbol: 'AVAX',
    explorerUrl: 'https://snowtrace.io',
  },
  {
    id: 'arbitrum-nova',
    name: 'Arbitrum Nova',
    alchemyNetwork: Network.ARBNOVA_MAINNET,
    coingeckoPlatform: 'arbitrum-nova',
    nativeSymbol: 'ETH',
    explorerUrl: 'https://nova.arbiscan.io',
  },
  {
    id: 'linea',
    name: 'Linea',
    alchemyNetwork: Network.LINEA_MAINNET,
    coingeckoPlatform: 'linea',
    nativeSymbol: 'ETH',
    explorerUrl: 'https://lineascan.build',
  },
  {
    id: 'zksync',
    name: 'zkSync Era',
    alchemyNetwork: Network.ZKSYNC_MAINNET,
    coingeckoPlatform: 'zksync',
    nativeSymbol: 'ETH',
    explorerUrl: 'https://era.zksync.network',
  },
  {
    id: 'fantom',
    name: 'Fantom',
    alchemyNetwork: Network.FANTOM_MAINNET,
    coingeckoPlatform: 'fantom',
    nativeSymbol: 'FTM',
    explorerUrl: 'https://ftmscan.com',
  },
  {
    id: 'scroll',
    name: 'Scroll',
    alchemyNetwork: Network.SCROLL_MAINNET,
    coingeckoPlatform: 'scroll',
    nativeSymbol: 'ETH',
    explorerUrl: 'https://scrollscan.com',
  },
  {
    id: 'gnosis',
    name: 'Gnosis',
    alchemyNetwork: Network.GNOSIS_MAINNET,
    coingeckoPlatform: 'xdai',
    nativeSymbol: 'xDAI',
    explorerUrl: 'https://gnosisscan.io',
  },
  {
    id: 'blast',
    name: 'Blast',
    alchemyNetwork: Network.BLAST_MAINNET,
    coingeckoPlatform: 'blast',
    nativeSymbol: 'ETH',
    explorerUrl: 'https://blastscan.io',
  },
  {
    id: 'mantle',
    name: 'Mantle',
    alchemyNetwork: Network.MANTLE_MAINNET,
    coingeckoPlatform: 'mantle',
    nativeSymbol: 'MNT',
    explorerUrl: 'https://mantlescan.xyz',
  },
  {
    id: 'celo',
    name: 'Celo',
    alchemyNetwork: Network.CELO_MAINNET,
    coingeckoPlatform: 'celo',
    nativeSymbol: 'CELO',
    explorerUrl: 'https://celoscan.io',
  },
  {
    id: 'polygon-zkevm',
    name: 'Polygon zkEVM',
    alchemyNetwork: Network.POLYGONZKEVM_MAINNET,
    coingeckoPlatform: 'polygon-zkevm',
    nativeSymbol: 'ETH',
    explorerUrl: 'https://zkevm.polygonscan.com',
  },
];

export const getChainById = (id: string): Chain | undefined => {
  return SUPPORTED_CHAINS.find((chain) => chain.id === id);
};
